## Hypothesis Testing Assignment

In [2]:
#Importing necessary packages
import pandas as pd
import numpy as np
# package with hypothesis tests
import scipy.stats as st

### Data

You can download the data from [**here**](https://drive.google.com/file/d/0Bz9_0VdXvv9bUUNlUTVrMF9VcVU/view?usp=sharing&resourcekey=0-16O9Fc5eaJH99-M7AHqHOg). The data contains results of all NBA games from seasons 2013/2014 to 2015/2016.

--------------
### Task 1
Split the data into **3** separate dataframes for each NBA season!

In [8]:
nba=pd.read_csv("C:\\Users\\bevli\\Downloads\\probability_and_statistics_exercise\\nba_games_2013_2015.csv", sep=';')
nba.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22015,1610612750,MIN,Minnesota Timberwolves,21501226,2016-04-13,MIN vs. NOP,W,240,144,...,0.826,5,38,43,41,14,8,13,20,35.0
1,22015,1610612749,MIL,Milwaukee Bucks,21501225,2016-04-13,MIL vs. IND,L,240,92,...,0.846,7,36,43,23,8,3,15,15,-5.0
2,22015,1610612738,BOS,Boston Celtics,21501217,2016-04-13,BOS vs. MIA,W,240,98,...,0.864,10,29,39,20,7,3,7,20,10.0
3,22015,1610612747,LAL,Los Angeles Lakers,21501228,2016-04-13,LAL vs. UTA,W,239,101,...,0.867,8,39,47,19,6,3,13,17,5.0
4,22015,1610612739,CLE,Cleveland Cavaliers,21501220,2016-04-13,CLE vs. DET,L,265,110,...,0.733,8,35,43,21,4,7,10,23,-2.0

In [9]:
nba['SEASON_ID'].unique()
nba13=nba[nba['SEASON_ID']==22013].copy()
nba14=nba[nba['SEASON_ID']==22014].copy()
nba15=nba[nba['SEASON_ID']==22015].copy()

---------------
### Task 2
Test the hypothesis that the offensive productions stats of the Cleveland Cavaliers and Golden State Warriors (the teams that met in the finals that year) were from the same distribution in the 2015/2016 season.

Offensive production refers to two variables: **PTS (Points)** and **FG_PCT (Field Goal Percentage)**. We will need to do two separate hypothesis tests, one for each variable.

In [12]:
gsw15=nba15[(nba15['TEAM_NAME'] == 'Golden State Warriors')]
cc15=nba15[(nba15['TEAM_NAME'] == 'Cleveland Cavaliers')]
gsw15.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
13,22015,1610612744,GSW,Golden State Warriors,21501227,2016-04-13,GSW vs. MEM,W,240,125,...,0.813,12,39,51,35,7,7,17,14,21.0
73,22015,1610612744,GSW,Golden State Warriors,21501201,2016-04-10,GSW @ SAS,W,238,92,...,0.778,7,39,46,19,7,6,13,18,6.0
74,22015,1610612744,GSW,Golden State Warriors,21501190,2016-04-09,GSW @ MEM,W,239,100,...,0.923,7,41,48,20,3,7,11,14,1.0
111,22015,1610612744,GSW,Golden State Warriors,21501177,2016-04-07,GSW vs. SAS,W,241,112,...,0.909,7,36,43,33,8,2,15,22,11.0
141,22015,1610612744,GSW,Golden State Warriors,21501163,2016-04-05,GSW vs. MIN,L,266,117,...,0.875,9,37,46,35,9,5,23,29,-7.0

In [16]:
# Null Hypothesis PTS(CC15) = PTS(GSW15)
cc15pts = cc15['PTS'].tolist()
gsw15pts = gsw15['PTS'].tolist()
ptest= st.stats.ttest_ind(cc15pts,gsw15pts)
print (ptest)
if ptest[1] > 0.05:
    print('accept null hypothesis')
elif ptest[1] < 0.05:
    print('reject null hypothesis')

Ttest_indResult(statistic=-5.973920595717936, pvalue=1.4233420547764935e-08)
reject null hypothesis

In [17]:
# Null Hypothesis FG_PCT(CC15) = FG_PCT(GSW15)
cc15fg = cc15['FG_PCT'].tolist()
gsw15fg = gsw15['FG_PCT'].tolist()
ptest= st.stats.ttest_ind(cc15fg,gsw15fg)
print (ptest)
if ptest[1] > 0.05:
    print('accept null hypothesis')
elif ptest[1] < 0.05:
    print('reject null hypothesis')

Ttest_indResult(statistic=-3.13195297595825, pvalue=0.00206097581047554)
reject null hypothesis

-----------------
### Task 3
Test the hypothesis that the number of points (PTS) scored by Cleveland Cavaliers changed significantly after the head coach changed in the 2015/2016 season.

- **Coach Blatt was fired on 24th of Jan, 2016**. 

Use the data from seasons 2014/2015 and 2015/2016 - those are years when Cleveland was coached by Blatt. 

**We have two possible solutions to try here:**
- Take the same amount of games from before and after and try t-test.
- Take all the games from before and after and look for the right test to compare two samples with different sizes. (You will need to go through the scipy documentation or google to figure out what kind of test is required.)

In [22]:
# Null Hypothesis (PTS beforeJan24,2016) > (PTS after Jan24,2016)
cc14_pts=nba14[(nba14['TEAM_NAME']== 'Cleveland Cavaliers')]
pts_14=cc14_pts['PTS'].tolist()

#Coach Blatt before fire in 2015, split year in 2 halves
cc15_pts_blatt=nba15[(nba15['TEAM_NAME'] == 'Cleveland Cavaliers')]
cc_blatt=cc15_pts_blatt[cc15_pts_blatt['GAME_DATE']<'2016-01-24']
pts_15_blatt = cc_blatt['PTS'].tolist()

#Coach blatt is fired, remainder season points after date to list
cc_noblatt=cc15_pts_blatt[cc15_pts_blatt['GAME_DATE']>'2016-01-24']
pts_15_noblatt=cc_noblatt['PTS'].tolist()

before= pts_14+pts_15_blatt
after=pts_15_noblatt

In [23]:
pvalue=st.stats.ttest_ind(before,after)[1]
if pvalue > 0.05:
    print('accept null hypothesis, points changed significantly after firing blatt')
elif pvalue < 0.05:
    print('reject Null Hypothesis, points did not change after firing blatt')

reject Null Hypothesis, points did not change after firing blatt

----------------


### Task 4
Download [**the similar dataset**](https://drive.google.com/file/d/0Bz9_0VdXvv9bRHhuRTI1aXBQcTA/view?usp=sharing&resourcekey=0-jGIaWyk0bXyECNSzB3x38w) with scores from playoff games in 2016.

In [25]:
playoffs16= pd.read_csv("C:\\Users\\bevli\\Downloads\\probability_and_statistics_exercise\\nba_playoff_games_2016.csv", sep =';')
playoffs16.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,42015,1610612739,CLE,Cleveland Cavaliers,41500407,2016-06-19,CLE @ GSW,W,241,93,...,0.840,9,39,48,17,7,6,11,15,4.0
1,42015,1610612744,GSW,Golden State Warriors,41500407,2016-06-19,GSW vs. CLE,L,239,89,...,0.769,7,32,39,22,7,5,10,23,-4.0
2,42015,1610612744,GSW,Golden State Warriors,41500406,2016-06-16,GSW @ CLE,L,238,101,...,0.690,9,26,35,19,5,3,14,25,-14.0
3,42015,1610612739,CLE,Cleveland Cavaliers,41500406,2016-06-16,CLE vs. GSW,W,240,115,...,0.781,8,37,45,24,12,7,10,25,14.0
4,42015,1610612739,CLE,Cleveland Cavaliers,41500405,2016-06-13,CLE @ GSW,W,241,112,...,0.609,8,33,41,15,11,9,16,22,15.0

------------
### Task 5
Test the hypothesis that **number of blocks (BLK)** are from the same distribution in both the NBA playoffs and in the NBA regular season for 2015/2016 seaon for the **Toronto Raptors**. 

- We will be working with two samples with different sizes again.

In [26]:
# Null Hypothesis: Number of BLK in season = playoffs for Toronto Raptors
tt15_reg=nba15[(nba15['TEAM_NAME']== 'Toronto Raptors')]
tt15_regblks=tt15_reg['BLK'].tolist()

tt15_playoffs=playoffs16[(playoffs16['TEAM_NAME']=='Toronto Raptors')]
tt15_playoffsblks=tt15_playoffs['BLK'].tolist()

pvalue=st.stats.ttest_ind(tt15_regblks,tt15_playoffsblks)[1]
if pvalue > 0.05:
    print('Accept null hypothesis, blocks are same')
elif pvalue < 0.05:
    print('Reject null hypothesis, blocks are diff')

Reject null hypothesis, blocks are diff


-----------------
### Task 6
Test the hypothesis that the number of points (PTS) scored by Cleveland Cavaliers is equally distributed for all 3 seasons. 

- In this case, we need a hypothesis test that compares more than 2 distributions at the same. (You will need to go through the scipy documentation or google to figure out what kind of test is required.)

In [27]:
cc13=nba13[(nba13['TEAM_NAME']=="Cleveland Cavaliers")]['PTS'].tolist()
cc14=nba14[(nba14['TEAM_NAME']=="Cleveland Cavaliers")]['PTS'].tolist()
cc15=nba15[(nba15['TEAM_NAME']=="Cleveland Cavaliers")]['PTS'].tolist()

In [28]:
pvalue= st.stats.f_oneway(cc13,cc14,cc15)[1]
if pvalue > 0.05:
    print("accept null hypothesis, is equally distributed")
else:
    print("reject null hypothesis, points are not equally distributed")

reject null hypothesis, points are not equally distributed

#### Follow Up
**Between which seasons can we see the significant difference?**

+ Unfortunatelly, this is not the output of an ANOVA test and further tests are needed to be run.
+ Note: Lebron James came back to the Cleveland Caveliers prior to season 2014/2015. We can use this fact to interpret our results correctly.